# What is Pandas?
Pandas is a [package](https://data36.com/python-import-built-in-modules-data-science/) in Python, used for data formatting, analysis and manipulation. It gives you a way to deal with 2-D data structures (like SQL or Excel tables) in Python, which isn't "native" to the language. That's why we have to `import` the package. In the jupyter hub installation of Python, you already have Pandas installed, we don't have to download it. By `import`-ing the package, we just allow the current .py or .ipynb file we're working on to use the functionality of the package.

### Why pandas?
- 2-D table-like data structures are intuitively known to us. Everyone is used to seeing Excel tables and this feels comfortable to work with. It is also what business people and other stakeholders will be used to seeing.
- It's one of the quickest ways to "automate the boring stuff" and lets you add value to any team quickly. 
- It plays well with other packages & libraries like `scikit-learn` and `matplotlib`.
- Excellent tools for transforming & cleaning data (i.e. resampling, filling missing values).

[For reference, you can use this great pandas cheat sheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf).

### When Pandas?

Here, we look at where pandas fits in the wider data science/analysis pipeline. This image shows that.

<img src="pics/ds_path.png">

[source](https://towardsdatascience.com/how-it-feels-to-learn-data-science-in-2019-6ee688498029)

<img src="./pics/data_science_path.png">

[source](https://medium.com/dunder-data/how-to-learn-pandas-108905ab4955)

Shortening pandas to `pd` is common.

In [1]:
import pandas as pd

In [2]:
pd.__version__

'1.1.1'

## Python data types

A quick review of the basic data structures in Python:

In [3]:
float(16)

16.0

In [4]:
int(16)

16

In [5]:
str(16)

'16'

In [6]:
bool(16)

True

In [7]:
bool(0)

False

In [8]:
bool(None)

False

In [9]:
list([1, 2, 3])

[1, 2, 3]

## Pandas Data Types

Pandas adds 2 more datatypes to ones that are native to Python:

- **pd.Series**:
    - 1-D data structure; single columns.

- **pd.DataFrame**:
    - 2-D data structure (better known as a table w/ named columns & numbered rows).
    
Here, we will focus on DataFrames:
- 2-D data structures are important to know how to work with in data science (you can't train a model with only 1 single array of data)

### Importing a DataFrame
Throughout this tutorial, we will make use of some practice data sets. Here, we use a dataset of wine reviews.  

We use the read_csv function to load data from a csv file into a DataFrame:

In [10]:
pwd # finding where we currently are in the file system

'/Users/rachelberryman/Desktop/DSR_25/Intro%20to%20Python'

In [5]:
wine = pd.read_csv('./data/wine/winemag-data_first150k.csv', 
                   index_col=0)

## 1. Leveraging Pandas for Data Understanding and Analysis

### Quickly viewing data

The DataFrame is a Python object, with useful methods (i.e. functions) and attributes (often referring to simpler Python data types like floats or tuples).

In [6]:
wine

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
...,...,...,...,...,...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

df.head() - shows first n rows (5 by default) _in order imported_! This is important as it is not sorted. So, the first row you see may not be the "actual" first row, or the first row you expect to see.

In [7]:
wine.head(n=10)

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia
6,Spain,Slightly gritty black-fruit aromas include a s...,San Román,95,65.0,Northern Spain,Toro,NaN,Tinta de Toro,Maurodos
7,Spain,Lush cedary black-fruit aromas are luxe and of...,Carodorum Único Crianza,95,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström
9,US,The producer sources from two blocks of the vi...,Gap's Crown Vineyard,95,60.0,California,Sonoma Coast,Sonoma,Pinot Noir,Blue Farm

df.tail() - shows last n rows in order of imported (below we limit it to three)

In [8]:
wine.tail(n=3)

,country,description,designation,points,price,province,region_1,region_2,variety,winery
150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

`df.shape` shows how many `(rows, columns)` we have. 


We can use the indexers to get just one of these.


**How many rows does our data have?**

In [15]:
wine.shape

(150930, 10)

In [16]:
rows = wine.shape[0]
rows

150930

### Exercise:
- Get the last 25 rows in the DataFrame
- Get the number of columns in the DataFrame. Save this as a new variable called "columns". Print the result.

We can also quickly look at the data types of each of our columns:
- each column has a single data type
- pandas has figured out some of our columns dtypes for us

In [17]:
wine.dtypes

country         object
description     object
designation     object
points           int64
price          float64
province        object
region_1        object
region_2        object
variety         object
winery          object
dtype: object

In [18]:
wine.head()

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

Also useful is df.describe() - a method which generates summary statistics of the columns:

In [19]:
wine.describe()

              points          price
count  150930.000000  137235.000000
mean       87.888418      33.131482
std         3.222392      36.322536
min        80.000000       4.000000
25%        86.000000      16.000000
50%        88.000000      24.000000
75%        90.000000      40.000000
max       100.000000    2300.000000

## What is a DataFrame made of?

Column names:

In [20]:
wine.columns

Index(['country', 'description', 'designation', 'points', 'price', 'province',
       'region_1', 'region_2', 'variety', 'winery'],
      dtype='object')

An index (similar to a primary key in SQL):

Difference with a primary key in SQL is that a primary key MUST be unique, an index in Pandas doesn't have to.

In [21]:
wine.index

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            150920, 150921, 150922, 150923, 150924, 150925, 150926, 150927,
            150928, 150929],
           dtype='int64', length=150930)

And data (stored as `values`)

In [22]:
wine.values[0]

array(['US',
       'This tremendous 100% varietal wine hails from Oakville and was aged over three years in oak. Juicy red-cherry fruit and a compelling hint of caramel greet the palate, framed by elegant, fine tannins and a subtle minty tone in the background. Balanced and rewarding from start to finish, it has years ahead of it to develop further nuance. Enjoy 2022–2030.',
       "Martha's Vineyard", 96, 235.0, 'California', 'Napa Valley',
       'Napa', 'Cabernet Sauvignon', 'Heitz'], dtype=object)

## Initial Data Exploration with Pandas
### Selecting Data
Anyone who has worked with data knows how important it is to be able to select particular columns or rows.
In Pandas, there are a lot of different ways to select.

### Selecting by column name
2 ways:

In [23]:
# 1. With quotes
wine['price']

0         235.0
1         110.0
2          90.0
3          65.0
4          66.0
          ...
150925     20.0
150926     27.0
150927     20.0
150928     52.0
150929     15.0
Name: price, Length: 150930, dtype: float64

In [24]:
# 2. With period (NOTE - ONLY works when column names have no spaces!)
wine.price

0         235.0
1         110.0
2          90.0
3          65.0
4          66.0
          ...
150925     20.0
150926     27.0
150927     20.0
150928     52.0
150929     15.0
Name: price, Length: 150930, dtype: float64

We can also chain together functions (commands) in Pandas:

In [25]:
wine[['price', 'points']].head()

   price  points
0  235.0      96
1  110.0      96
2   90.0      96
3   65.0      96
4   66.0      95

### Exercise:
- Select the columns "region_2" and "variety".

## Slicing - Precise Selection by Row and Column
- `df.loc` gets rows (or columns) with particular labels from the index.
- `df.iloc` gets rows (or columns) at particular positions in the index (so it only takes integers).


**When using `loc` and `iloc`, the row is ALWAYS 1st and column is ALWAYS second!!**

**[row:row, column:column]**

Notice how each defaults if you leave one side blank.

In [26]:
wine.iloc[:5,]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude

In [27]:
wine.loc[:5]

,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia

To see how these two are different, we will change the index.

In [28]:
# saving the original index for when we re-index later
wine.loc[:,'index'] = wine.index

In [29]:
import random

In [30]:
random_index = random.sample(list(wine.index), k=len(list(wine.index)))
wine['scrambled_index'] = random_index
scrambled_wine = wine.set_index('scrambled_index')

In [31]:
# returns all rows up to the 5th position.
scrambled_wine.iloc[:5]

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index
scrambled_index,,,,,,,,,,,
142213,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,0
22187,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,1
120847,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,2
76234,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,3
12041,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,4

In [32]:
# returns all rows up to where #5 is in the index. Since we scrambled it, this is no longer in the 5th position.
scrambled_wine.loc[:5]

,country,description,designation,points,price,province,region_1,region_2,variety,winery,index
scrambled_index,,,,,,,,,,,
142213,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz,0
22187,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez,1
120847,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley,2
76234,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi,3
12041,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude,4
...,...,...,...,...,...,...,...,...,...,...,...
44723,US,"Firm and compact, it mixes wild berry, plum an...",DuBrul Vineyard Carriage House Red,90,50.0,Washington,Yakima Valley,Columbia Valley,Red Blend,Côte Bonneville,56953
78699,US,Great price for a Zin of this purity and varie...,NaN,90,20.0,California,Sonoma Valley,Sonoma,Zinfandel,Cline,56954
96931,US,"A delicate, silky and sensual Pinot Noir that ...",NaN,90,20.0,California,Sonoma County,Sonoma,Pinot Noir,Chateau St. Jean,56955
124948,France,This rich botrytized wine is certainly sweet. ...,Les Churelles de Juchepie,90,30.0,Loire Valley,Coteaux du Layon La Faye,NaN,Chenin Blanc,Domaine de Juchepie,56956
5,US,Old vine fruit from Sagemoor and Kiona blends ...,Big Papa Old Vine,90,45.0,Washington,Columbia Valley (WA),Columbia Valley,Cabernet Sauvignon,Efeste,56957

Including columns:

In [33]:
scrambled_wine.iloc[:5, :5]

,country,description,designation,points,price
scrambled_index,,,,,
142213,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0
22187,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0
120847,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0
76234,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0
12041,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0

**Question:**
What happens when you try to use `.loc` with column selectors, instead of `.iloc`?

In [34]:
scrambled_wine.loc[5:10,:'price']

,country,description,designation,points,price
scrambled_index,,,,,
5,US,Old vine fruit from Sagemoor and Kiona blends ...,Big Papa Old Vine,90,45.0
15874,US,"Sharp scents with a light hint of cardboard, p...",NaN,90,14.0
37150,Australia,"This blend of 63% Shiraz, 18% Cabernet Sauvign...",Keyneton Estate Euphonium,90,45.0
123807,US,"This is 100% varietal, all Lewis vineyard frui...",NaN,90,32.0
16572,Italy,Shardana is a joint venture between Sardinia's...,Shardana,90,30.0
...,...,...,...,...,...
128340,US,Displays good terroir qualities of extraordina...,NaN,92,32.0
108383,US,The most successful 2006 Pinot in Argyle's lin...,Reserve,92,43.0
103859,US,"This is a very dense, bone dry and full-bodied...",Esola Vineyard,92,44.0
54457,France,"Poised between a rich, soft Pinot Noir and one...",Beaune Aigrots Premier Cru,92,75.0
10,US,This bottling has been remarkably consistent f...,Artistry,92,42.0

With `df.loc`, we can also use key words.

**Question:** Why doesn't the same work with `.iloc`?

## Exercise:
- Select the first 5 rows, and first 2 columns, positionally. 
- Select rows 10, 15, ans 30, and the columns "points" and "price".
- Select the first 5 rows and columns "points" and "region_1" of the *scrambled_wine* table. Hint: you'll need to string together 2 different types of selectors.